version: '3.0'
services:
  buildroot:
    restart: always
    build:
      context: ./buildroot
    environment:
      - MY_ENV_VAR=my_value
    volumes:
      - "./buildroot/configs/:/opt/buildroot/configs"

